In [1]:
print('Hello World')

Hello World


In [2]:
from numpy import np
x = np.array([1,2,3,4])

ModuleNotFoundError: No module named 'numpy'

In [3]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [4]:
import numpy as np

In [5]:
x = np.array([1,2,3,4])

In [6]:
print(x)

[1 2 3 4]


In [7]:
type(x)

numpy.ndarray

In [8]:
y = [1,2,3,4]
print(y)
type(y)

[1, 2, 3, 4]


list

In [9]:
x == y

array([ True,  True,  True,  True])

In [10]:
print(x)

[1 2 3 4]


In [11]:
print(y)

[1, 2, 3, 4]


In [12]:
print(x == y)

[ True  True  True  True]


In [13]:
type(x)
type(y)

list

In [14]:
type(x)

numpy.ndarray

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
z = np.arange(10)

In [18]:
print(z)
type(z)
print(x)
type(x)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4]


numpy.ndarray

In [19]:
type(z)

numpy.ndarray

In [20]:
type(x)

numpy.ndarray

In [22]:
np.array([5,4,3,2,1])

array([5, 4, 3, 2, 1])

In [23]:
x = np.array(['tin','to','tun','mee'])

In [24]:
print(x)

['tin' 'to' 'tun' 'mee']


In [25]:
y = np.arange(4,12,1)
print(y)

[ 4  5  6  7  8  9 10 11]


## Class

In [33]:
class BNKMember:
    gender = 'Female'
    year = 0
    def add_year(self,year_to_add):
        self.year = self.year + year_to_add

In [28]:
BNKMember

__main__.BNKMember

In [35]:
mobile = BNKMember()

In [31]:
print(mobile.gender)

Female


In [36]:
mobile.add_year(18)

In [37]:
mobile.year

18

In [38]:
sum_and_multiply = lambda a,b : (a+b)*b

In [39]:
sum_and_multiply(1,2)

6